### ISSUE TITLE
multiple "." in input - wrong conversion

### ISSUE THREAD

**Issue by netengine-at** [QODIO/numbertor#2]
**Version**
1.1, Dec 11th, 2015

**Reproducible on**
Input field "default" on http://opensource.qodio.com/numbertor/

**Example of a correct conversion**
input in field: 150000
converted to - on leave: 150.000
converted to - on focus: 150000

**Example of a wrong conversion**
input in field: 1500000
converted to - on leave: 1.500.000
converted to - on focus: 1500

**replace() Method**
If you are replacing a value (and not a regular expression), only the first instance of the value will be replaced. To replace all occurrences of a specified value, use the global (g) modifier (see "More Examples" below).
https://www.w3schools.com/jsref/jsref_replace.asp

**String replacement in script**
Line 75 - _.replace(thousandSeperator, '')_ and _.replace(decimalSeperator, '.')_
`number = number.replace(/[^0-9,\.]/g,'').replace(thousandSeperator, '').replace(decimalSeperator, '.');`

Line 89 - _.replace(thousandSeperator, '')_ and _.replace(decimalSeperator, '.')_ and _.replace('.', decimalSeperator)_
`number = parseFloat(number.toString().replace(/\s/g, '').replace(thousandSeperator, '').replace(decimalSeperator, '.')).toString().replace('.', decimalSeperator);`

**Comment by jogvana** [comment]
Thanks for the feedback. We'll look at this asap.

**Comment by ingipingi** [comment]
This issue should be fixed now
